name: qwen_eval
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - expat=2.7.3
  - libcxx=20.1.8
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bitsandbytes==0.42.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - datasets==4.4.1
      - dill==0.4.0
      - filelock==3.20.0
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.0.0
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - pyarrow==22.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scipy==1.15.3
      - sympy==1.14.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.6.0
      - yarl==1.22.0
